#arthemetic operator ex:
a=float(input("Enter Value of A:"))
b=float(input("Enter Value of B:"))
m=float(input("Enter Value of M:"))
n=float(input("Enter Value of N:"))
print("*"*50)
print("*"*50)
print("A r t h e m e t i c O p e r a t i o n s")
print("*"*50)
print("Sum({},{})={}".format(a,b,a+b))
print("*"*50)
print("sub({},{})={}".format(a,b,a-b))
print("*"*50)
print("mul({},{})={}".format(a,b,a*b))
print("*"*50)
print("div({},{})={}".format(a,b,a/b))
print("*"*50)
print("F div({},{})={}".format(a,b,a//b))
print("*"*50)
print("M div({},{})={}".format(a,b,a%b))
print("*"*50)
print("expo({},{})={}".format(a,b,a**b))
print("*"*50)
print("sqrt({})={}".format(a,a**(0.5)))
print("*"*50)
print("cube({})={}".format(a,a**(0.333)))
print("*"*50)
print("expo({},{})={}".format(m,n,m**n))
print("*"*50)
print("*"*50)
