#LOGICAL OPERATORS
a=float(input("Enter value of A:"))
b=float(input("Enter value of B:"))
c=bool(input("Enter value of c:"))
print("="*50)
print("="*50)
print("{} or {} is {},{}".format(a,b,(a) or (b),c))
print("="*50)
print("{} and {} is {},{}".format(a,b,(a) and (b),c))
print("="*50)
print("="*50)
print("="*50)
print("{} NOT >= {} is {}".format(a,b,not((a)>=(b))))
print("="*50)
print("{} NOT <= {} is {}".format(a,b,not((a)<=(b))))
print("="*50)
print("{} NOT == {} is {}".format(a,b,not((a)==(b))))
print("="*50)
print("{} NOT != {} is {}".format(a,b,not((a)!=(b))))
print("="*50)
print("{} NOT > {} is {}".format(a,b,not((a)>(b))))
print("="*50)
print("{} NOT < {} is {}".format(a,b,not((a)<(b))))
print("="*50)
print("="*50)
