# TO ACCEPT STNO,STNAME,MARKS,CLG NAME
stno=int(input("ENTER STUDENT NO : "))
stname=input("ENTER STUDENT NAME : ")
stmarks=float(input("ENTER STUDENT CGPA : "))
stclg=input("ENTER STUDENT COLLEGE NAME : ")
print("----"*60)
print("----"*60)
print("---------------------------DETAILS OF STUDENT--------------------------------")
print("STUDENT NO= {}".format(stno))
print("STUDENT NAME= {}".format(stname))
print("STUDENT CGPA= {}".format(stmarks))
print("STUDENT CLG= {}".format(stclg))
print("----"*60)
print("----"*60)
print("----"*60)
